version: '3'

services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command: >
      bash -c "dotnet dev-certs https
      && dotnet run"
    working_dir: /app
    network_mode: bridge
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4000:7290"

  suggestieservice:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    network_mode: bridge
    command: >
      bash -c "dotnet dev-certs https
      && dotnet run"
    working_dir: /app
    depends_on:
      - database
      - backend
    volumes:
      - ./suggestieservice:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4001:7290"
    links:
      - backend

  database:
    image: mysql
    network_mode: bridge
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=backend
      - MYSQL_USER=backend
      - MYSQL_PASSWORD=123456
    volumes:
      - database:/var/lib/mysql

  frontend:
    image: node
    command: ["npm", "start"]
    network_mode: bridge
    working_dir: /app
    links:
      - backend
      - suggestieservice
    depends_on:
      - backend
      - suggestieservice
    volumes:
      - ./frontend:/app
      - /C/Users/Eric/AppData/Roaming/ASP.NET/https:/Users/Eric/.aspnet/https
      - /C/Users/Eric/AppData/Roaming/ASP.NET/https:/root/.aspnet/https
    ports:
      - "4002:44489"

volumes:
  database: